### PR TITLE
addition features

### PR DESCRIPTION
**Pull request by saurabhkapur**
added ship of length 2

### CODE REVIEW

**Comment by sbshah97** [comment]
Hey, nice change but instead of making the ship of length 2 can u make multiple ships instead?

**Comment by saurabhkapur** [comment]
But I don't see any use AI when the length of the ship is 1 because when the length is 1 the position of the ship can be random

**Comment by sbshah97** [comment]
Good point. How about multiple ships with various lengths?

**Comment by saurabhkapur** [comment]
yes that is why I started by adding one ship of length 2 initially and then add multiple ships of various lengths

**Comment by sbshah97** [comment]
Umm. Okay can you resend the Pull Request if that isn't a problem.

**Pull request closed without merging**
